baseURL = "https://adilio.ca"
languageCode = "en-us"
theme = "poison"
paginate = 10
pluralizelisttitles = false

[params]
    brand = "adilio.ca"
    brand_image = "/img/adil-cartoon-headshot.png"
    description = "Cloud Solutions Architect Â· Automation Advocate"
    dark_mode = true

    [[params.menu]]
        name = "About"
        url = "/about/"

    [[params.menu]]
        name = "Blog"
        url = "/posts/"

    # Social links
    [[params.social]]
        name = "Github"
        url = "https://github.com/adilio"

    [[params.social]]
        name = "Twitter"
        url = "https://twitter.com/adilio"

    [[params.social]]
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/adilio"

[taxonomies]
    series = "series"
    tag = "tags"
