baseURL = "https://adilio.ca"
languageCode = "en-us"
theme = "poison"
pluralizelisttitles = false

[pagination]
    pagerSize = 10

[params]
    brand = "adilio.ca"
    brand_image = "/img/adil-cartoon-headshot.png"
    description = "Cloud Solutions Architect Â· Automation Advocate"
    dark_mode = true

    [[params.menu]]
        Name = "About"
        URL = "/about/"

    [[params.menu]]
        Name = "Blog"
        URL = "/posts/"

    [[params.menu]]
        Name = "Projects"
        URL = "/projects/"

    [[params.menu]]
        Name = "Apps"
        URL = "/apps/"

    [[params.menu]]
        Name = "Talks"
        URL = "/talks/"

    # Social links
    [[params.social]]
        name = "Github"
        url = "https://github.com/adilio"

    [[params.social]]
        name = "Twitter"
        url = "https://twitter.com/adilio"

    [[params.social]]
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/adilio"

    [[params.social]]
        name = "Bluesky"
        url = "https://bsky.app/profile/adilio.ca"

[taxonomies]
    series = "series"
    tag = "tags"
